# Generated by Django 4.1 on 2022-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendafecha',
            name='estado',
            field=models.CharField(max_length=9),
        ),
    ]
